"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import Nav from "../../components/Nav";
import Footer from "../../components/Footer";

interface StoryData {
  headline: string;
  story: string;
  moral: string;
  date: string;
  category?: string;
}

function FictionBanner() {
  return (
    <div
      style={{
        background: "#FF3333",
        color: "#FFFFFF",
        fontSize: "0.85rem",
        fontWeight: 900,
        letterSpacing: "0.2em",
        textTransform: "uppercase",
        padding: "16px 24px",
        textAlign: "center",
        width: "100%",
        boxSizing: "border-box",
      }}
    >
      THIS IS A WORK OF FICTION — AI-generated from an anonymous submission. All details are fictional.
    </div>
  );
}

function NoStory() {
  return (
    <div style={{ background: "#0A0A0A", minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      <Nav />
      <div
        style={{
          flex: 1,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "80px 24px",
          textAlign: "center",
          flexDirection: "column",
          gap: "24px",
        }}
      >
        <h1
          style={{
            fontFamily: "var(--font-bebas), 'Arial Black', Arial, sans-serif",
            fontSize: "clamp(2.5rem, 8vw, 5rem)",
            color: "#F0F0F0",
            margin: 0,
            letterSpacing: "0.02em",
          }}
        >
          NO STORY FOUND
        </h1>
        <p style={{ color: "#888888", fontSize: "1rem", lineHeight: 1.7, maxWidth: "480px", margin: 0 }}>
          This link doesn&rsquo;t have a story attached, or the data got mangled somewhere. Try opening
          it again from the original source.
        </p>
        <Link
          href="/submit-drama"
          style={{
            background: "#FFD700",
            color: "#0A0A0A",
            textDecoration: "none",
            padding: "16px 40px",
            fontFamily: "var(--font-bebas), Arial, sans-serif",
            fontSize: "1.2rem",
            letterSpacing: "0.1em",
            display: "inline-block",
            marginTop: "8px",
          }}
        >
          SUBMIT YOUR OWN DRAMA
        </Link>
      </div>
      <Footer />
    </div>
  );
}

function RenderStory({ data }: { data: StoryData }) {
  const [linkCopied, setLinkCopied] = useState(false);

  const formattedDate = (() => {
    try {
      return new Date(data.date).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    } catch {
      return "Recently";
    }
  })();

  async function handleCopyLink() {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2500);
    } catch {
      setLinkCopied(false);
    }
  }

  function getTwitterShareUrl() {
    const text = encodeURIComponent(`"${data.headline}" — AI fiction from an anonymous submission:`);
    const url = encodeURIComponent(window.location.href);
    return `https://twitter.com/intent/tweet?text=${text}&url=${url}`;
  }

  const metaDesc = data.story.replace(/\s+/g, " ").slice(0, 155) + "…";

  return (
    <>
      {/* Schema.org structured data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            headline: data.headline,
            description: metaDesc,
            datePublished: data.date,
            publisher: {
              "@type": "Organization",
              name: "Spaghetti Burritos",
              url: "https://spaghettiburritos.com",
            },
            mainEntityOfPage: {
              "@type": "WebPage",
              "@id": typeof window !== "undefined" ? window.location.href : "",
            },
          }),
        }}
      />

      <div style={{ background: "#0A0A0A", minHeight: "100vh", display: "flex", flexDirection: "column" }}>
        <Nav />

        {/* FICTION BANNER — impossible to miss */}
        <FictionBanner />

        {/* Disclaimer strip */}
        <div
          style={{
            background: "#0F0F0F",
            borderBottom: "1px solid rgba(255,51,51,0.2)",
            padding: "14px 24px",
            textAlign: "center",
          }}
        >
          <p
            style={{
              color: "#888888",
              fontSize: "0.78rem",
              lineHeight: 1.6,
              margin: "0 auto",
              maxWidth: "820px",
              fontFamily: "var(--font-inter), Arial, sans-serif",
            }}
          >
            This story was generated by AI from an anonymous submission. All details are fictional.
            Any resemblance to actual persons, living or dead, is purely coincidental.
            Spaghetti Burritos shaped the fiction — the raw drama came from someone else.
          </p>
        </div>

        {/* Main article */}
        <main
          style={{
            flex: 1,
            maxWidth: "740px",
            margin: "0 auto",
            padding: "48px 24px 80px",
            width: "100%",
            boxSizing: "border-box",
          }}
        >
          <article>
            <header>
              {/* Meta row */}
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "16px",
                  flexWrap: "wrap",
                  marginBottom: "24px",
                }}
              >
                {data.category && (
                  <span
                    style={{
                      background: "rgba(255,215,0,0.1)",
                      border: "1px solid rgba(255,215,0,0.3)",
                      color: "#FFD700",
                      fontSize: "0.7rem",
                      fontWeight: 700,
                      letterSpacing: "0.15em",
                      textTransform: "uppercase",
                      padding: "3px 10px",
                      fontFamily: "var(--font-bebas), Arial, sans-serif",
                    }}
                  >
                    {data.category}
                  </span>
                )}
                <span
                  style={{
                    color: "#555555",
                    fontSize: "0.78rem",
                    letterSpacing: "0.08em",
                    textTransform: "uppercase",
                    fontFamily: "var(--font-bebas), Arial, sans-serif",
                  }}
                >
                  Published {formattedDate}
                </span>
              </div>

              {/* H1 headline */}
              <h1
                style={{
                  fontFamily: "var(--font-bebas), 'Arial Black', Arial, sans-serif",
                  fontSize: "clamp(2.5rem, 7vw, 5rem)",
                  lineHeight: 0.95,
                  color: "#FFD700",
                  margin: "0 0 40px",
                  letterSpacing: "0.02em",
                }}
              >
                {data.headline}
              </h1>
            </header>

            {/* Story body */}
            <section>
              <div
                style={{
                  color: "#D0D0D0",
                  fontSize: "1.05rem",
                  lineHeight: 1.9,
                  marginBottom: "40px",
                  fontFamily: "var(--font-inter), Arial, sans-serif",
                }}
              >
                {data.story.split("\n").map((para, i) =>
                  para.trim() ? (
                    <p key={i} style={{ margin: "0 0 1.4em" }}>
                      {para}
                    </p>
                  ) : null
                )}
              </div>
            </section>

            {/* Moral */}
            <aside
              style={{
                borderLeft: "4px solid #FFD700",
                paddingLeft: "24px",
                marginBottom: "60px",
              }}
            >
              <p
                style={{
                  color: "#888888",
                  fontSize: "0.8rem",
                  fontWeight: 700,
                  letterSpacing: "0.15em",
                  textTransform: "uppercase",
                  margin: "0 0 8px",
                  fontFamily: "var(--font-bebas), Arial, sans-serif",
                }}
              >
                Moral of the Story
              </p>
              <p
                style={{
                  color: "#D0D0D0",
                  fontSize: "1.05rem",
                  lineHeight: 1.7,
                  fontStyle: "italic",
                  margin: 0,
                  fontFamily: "var(--font-inter), Arial, sans-serif",
                }}
              >
                {data.moral}
              </p>
            </aside>
          </article>

          {/* Share */}
          <div
            style={{
              borderTop: "1px solid rgba(255,215,0,0.15)",
              paddingTop: "32px",
              marginBottom: "60px",
            }}
          >
            <p
              style={{
                fontFamily: "var(--font-bebas), Arial, sans-serif",
                fontSize: "0.9rem",
                letterSpacing: "0.15em",
                color: "#888888",
                margin: "0 0 16px",
                textTransform: "uppercase",
              }}
            >
              Share This Story
            </p>
            <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
              <button
                onClick={handleCopyLink}
                style={{
                  background: linkCopied ? "#333333" : "#FFD700",
                  color: linkCopied ? "#F0F0F0" : "#0A0A0A",
                  border: "none",
                  padding: "12px 28px",
                  fontFamily: "var(--font-bebas), Arial, sans-serif",
                  fontSize: "1rem",
                  letterSpacing: "0.1em",
                  cursor: "pointer",
                  transition: "background 0.2s, color 0.2s",
                }}
              >
                {linkCopied ? "LINK COPIED" : "COPY LINK"}
              </button>
              <a
                href={getTwitterShareUrl()}
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  background: "#1DA1F2",
                  color: "#FFFFFF",
                  textDecoration: "none",
                  padding: "12px 28px",
                  fontFamily: "var(--font-bebas), Arial, sans-serif",
                  fontSize: "1rem",
                  letterSpacing: "0.1em",
                  display: "inline-block",
                  transition: "background 0.2s",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.background = "#1a8fd1")}
                onMouseLeave={(e) => (e.currentTarget.style.background = "#1DA1F2")}
              >
                SHARE ON X
              </a>
            </div>
          </div>

          {/* Internal backlinks — "More from Spaghetti Burritos" */}
          <div
            style={{
              background: "#0F0F0F",
              border: "1px solid rgba(255,215,0,0.1)",
              padding: "28px",
              marginBottom: "40px",
            }}
          >
            <p
              style={{
                fontFamily: "var(--font-bebas), Arial, sans-serif",
                fontSize: "0.85rem",
                letterSpacing: "0.2em",
                color: "#555555",
                margin: "0 0 16px",
                textTransform: "uppercase",
              }}
            >
              More from Spaghetti Burritos
            </p>
            <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
              <p style={{ margin: 0, fontSize: "0.9rem", color: "#AAAAAA", fontFamily: "var(--font-inter), Arial, sans-serif" }}>
                More AI-generated chaos lives at{" "}
                <a
                  href="https://spaghettiburritos.com"
                  style={{ color: "#FFD700", textDecoration: "none" }}
                  onMouseEnter={(e) => (e.currentTarget.style.textDecoration = "underline")}
                  onMouseLeave={(e) => (e.currentTarget.style.textDecoration = "none")}
                >
                  Spaghetti Burritos
                </a>
                {" "}— the internet&rsquo;s premier source of fictional nonsense.
              </p>
              <p style={{ margin: 0, fontSize: "0.9rem", color: "#AAAAAA", fontFamily: "var(--font-inter), Arial, sans-serif" }}>
                Got your own situation?{" "}
                <a
                  href="https://spaghettiburritos.com/submit-drama"
                  style={{ color: "#FFD700", textDecoration: "none" }}
                  onMouseEnter={(e) => (e.currentTarget.style.textDecoration = "underline")}
                  onMouseLeave={(e) => (e.currentTarget.style.textDecoration = "none")}
                >
                  Submit your drama
                </a>
                {" "}and let the AI turn it into something beautiful.
              </p>
            </div>
          </div>

          {/* CTA block */}
          <div
            style={{
              background: "#141414",
              border: "2px solid rgba(255,215,0,0.2)",
              padding: "40px",
              textAlign: "center",
            }}
          >
            <h2
              style={{
                fontFamily: "var(--font-bebas), 'Arial Black', Arial, sans-serif",
                fontSize: "clamp(1.8rem, 5vw, 3rem)",
                color: "#F0F0F0",
                margin: "0 0 12px",
                letterSpacing: "0.02em",
              }}
            >
              GOT YOUR OWN <span style={{ color: "#FFD700" }}>DRAMA?</span>
            </h2>
            <p
              style={{
                color: "#888888",
                fontSize: "0.95rem",
                lineHeight: 1.7,
                margin: "0 0 24px",
                fontFamily: "var(--font-inter), Arial, sans-serif",
              }}
            >
              Drop the tea. Our AI turns your mess into a masterpiece.
            </p>
            <Link
              href="/submit-drama"
              style={{
                background: "#FFD700",
                color: "#0A0A0A",
                textDecoration: "none",
                padding: "16px 40px",
                fontFamily: "var(--font-bebas), Arial, sans-serif",
                fontSize: "1.2rem",
                letterSpacing: "0.1em",
                display: "inline-block",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.background = "#FFC200")}
              onMouseLeave={(e) => (e.currentTarget.style.background = "#FFD700")}
            >
              SUBMIT YOUR DRAMA
            </Link>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
}

export default function StoryViewer({ slug }: { slug: string }) {
  const [storyData, setStoryData] = useState<StoryData | null | "loading" | "error">("loading");

  useEffect(() => {
    // Story data lives in the URL hash fragment
    const hash = window.location.hash.slice(1); // strip leading #
    if (!hash) {
      setStoryData("error");
      return;
    }
    try {
      const decoded = JSON.parse(decodeURIComponent(atob(hash)));
      if (!decoded.headline || !decoded.story || !decoded.moral) {
        setStoryData("error");
        return;
      }
      setStoryData(decoded);
    } catch {
      setStoryData("error");
    }
  }, [slug]);

  if (storyData === "loading") {
    return (
      <div
        style={{
          background: "#0A0A0A",
          minHeight: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <p
          style={{
            fontFamily: "var(--font-bebas), Arial, sans-serif",
            fontSize: "1.5rem",
            letterSpacing: "0.1em",
            color: "#555555",
          }}
        >
          LOADING...
        </p>
      </div>
    );
  }

  if (storyData === "error" || !storyData) return <NoStory />;

  return <RenderStory data={storyData} />;
}
