import { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { redditStories } from '../../data/reddit-stories';

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  return redditStories.map((story) => ({ slug: story.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const story = redditStories.find((s) => s.slug === slug);

  if (!story) {
    return {
      title: 'Story Not Found | Spaghetti Burritos',
    };
  }

  const description = `${story.story.slice(0, 155)}... Inspired by Reddit. AI-generated fiction. All names and details are fictional.`;

  return {
    title: `${story.headline} | Spaghetti Burritos`,
    description,
    openGraph: {
      title: story.headline,
      description,
      type: 'article',
      siteName: 'Spaghetti Burritos',
      url: `https://spaghettiburritos.com/reddit/${story.slug}`,
    },
    twitter: {
      card: 'summary_large_image',
      title: story.headline,
      description,
    },
    robots: { index: true, follow: true },
  };
}

export default async function RedditStoryPage({ params }: Props) {
  const { slug } = await params;
  const story = redditStories.find((s) => s.slug === slug);

  if (!story) {
    notFound();
  }

  const formattedDate = new Date(story.date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const metaDesc = story.story.replace(/\s+/g, ' ').slice(0, 155) + '...';

  const schemaData = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: story.headline,
    description: metaDesc,
    datePublished: story.date,
    publisher: {
      '@type': 'Organization',
      name: 'Spaghetti Burritos',
      url: 'https://spaghettiburritos.com',
    },
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': `https://spaghettiburritos.com/reddit/${story.slug}`,
    },
    keywords: `fiction, AI story, ${story.category}, inspired by Reddit, r/${story.subreddit}`,
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }}
      />

      <div style={{ background: '#0A0A0A', minHeight: '100vh' }}>

        {/* FICTION BANNER */}
        <div style={{
          background: '#FF3333',
          padding: '16px 24px',
          textAlign: 'center',
          width: '100%',
          boxSizing: 'border-box',
        }}>
          <p style={{
            color: '#FFFFFF',
            fontSize: '0.85rem',
            fontWeight: 900,
            letterSpacing: '0.2em',
            textTransform: 'uppercase',
            margin: 0,
            fontFamily: 'var(--font-inter), Arial, sans-serif',
          }}>
            THIS IS A WORK OF FICTION — AI-generated, inspired by general internet themes. All details are fictional.
          </p>
        </div>

        {/* DISCLAIMER STRIP */}
        <div style={{
          background: '#0F0F0F',
          borderBottom: '1px solid rgba(255,51,51,0.2)',
          padding: '14px 24px',
          textAlign: 'center',
        }}>
          <p style={{
            color: '#888888',
            fontSize: '0.78rem',
            lineHeight: 1.6,
            margin: '0 auto',
            maxWidth: '820px',
            fontFamily: 'var(--font-inter), Arial, sans-serif',
          }}>
            This story was generated by AI and is a work of fiction. It is inspired by the general themes
            of public internet discussions but is not a reproduction or summary of any real post.
            All names, locations, and events are invented.
          </p>
        </div>

        {/* MAIN ARTICLE */}
        <main style={{
          maxWidth: '740px',
          margin: '0 auto',
          padding: '48px 24px 80px',
          width: '100%',
          boxSizing: 'border-box',
        }}>
          <article>
            <header>
              {/* Back link */}
              <div style={{ marginBottom: '32px' }}>
                <Link href="/reddit" style={{
                  color: '#555555',
                  textDecoration: 'none',
                  fontSize: '0.78rem',
                  letterSpacing: '0.1em',
                  textTransform: 'uppercase',
                  fontFamily: 'var(--font-bebas), Arial, sans-serif',
                }}
                >
                  &larr; All Reddit Fiction
                </Link>
              </div>

              {/* Meta row */}
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '16px',
                flexWrap: 'wrap',
                marginBottom: '24px',
              }}>
                <span style={{
                  background: 'rgba(255,215,0,0.1)',
                  border: '1px solid rgba(255,215,0,0.3)',
                  color: '#FFD700',
                  fontSize: '0.7rem',
                  fontWeight: 700,
                  letterSpacing: '0.15em',
                  textTransform: 'uppercase',
                  padding: '3px 10px',
                  fontFamily: 'var(--font-bebas), Arial, sans-serif',
                }}>
                  {story.category}
                </span>
                <a
                  href={story.redditUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{
                    color: '#FF6B35',
                    fontSize: '0.78rem',
                    textDecoration: 'none',
                    letterSpacing: '0.06em',
                    fontFamily: 'var(--font-inter), Arial, sans-serif',
                  }}
                >
                  Inspired by a post on r/{story.subreddit} &rarr;
                </a>
                <span style={{
                  color: '#555555',
                  fontSize: '0.78rem',
                  letterSpacing: '0.08em',
                  textTransform: 'uppercase',
                  fontFamily: 'var(--font-bebas), Arial, sans-serif',
                  marginLeft: 'auto',
                }}>
                  {formattedDate}
                </span>
              </div>

              {/* Headline */}
              <h1 style={{
                fontFamily: 'var(--font-bebas), "Arial Black", Arial, sans-serif',
                fontSize: 'clamp(2.5rem, 7vw, 5rem)',
                lineHeight: 0.95,
                color: '#FFD700',
                margin: '0 0 40px',
                letterSpacing: '0.02em',
              }}>
                {story.headline}
              </h1>
            </header>

            {/* Story body */}
            <section>
              <div style={{
                color: '#D0D0D0',
                fontSize: '1.05rem',
                lineHeight: 1.9,
                marginBottom: '40px',
                fontFamily: 'var(--font-inter), Arial, sans-serif',
              }}>
                {story.story.split('\n').map((para, i) =>
                  para.trim() ? (
                    <p key={i} style={{ margin: '0 0 1.4em' }}>
                      {para}
                    </p>
                  ) : null
                )}
              </div>
            </section>

            {/* Moral */}
            <aside style={{
              borderLeft: '4px solid #FFD700',
              paddingLeft: '24px',
              marginBottom: '48px',
            }}>
              <p style={{
                color: '#888888',
                fontSize: '0.8rem',
                fontWeight: 700,
                letterSpacing: '0.15em',
                textTransform: 'uppercase',
                margin: '0 0 8px',
                fontFamily: 'var(--font-bebas), Arial, sans-serif',
              }}>
                Moral of the Story
              </p>
              <p style={{
                color: '#D0D0D0',
                fontSize: '1.05rem',
                lineHeight: 1.7,
                fontStyle: 'italic',
                margin: 0,
                fontFamily: 'var(--font-inter), Arial, sans-serif',
              }}>
                {story.moral}
              </p>
            </aside>

            {/* Attribution */}
            <div style={{
              background: '#0F0F0F',
              border: '1px solid rgba(255,107,53,0.2)',
              padding: '20px 24px',
              marginBottom: '48px',
            }}>
              <p style={{
                color: '#555555',
                fontSize: '0.78rem',
                letterSpacing: '0.1em',
                textTransform: 'uppercase',
                margin: '0 0 8px',
                fontFamily: 'var(--font-bebas), Arial, sans-serif',
              }}>
                Attribution
              </p>
              <p style={{
                color: '#888888',
                fontSize: '0.85rem',
                lineHeight: 1.6,
                margin: 0,
                fontFamily: 'var(--font-inter), Arial, sans-serif',
              }}>
                This work of fiction was inspired by the general themes discussed on{' '}
                <a
                  href={story.redditUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: '#FF6B35', textDecoration: 'none' }}
                >
                  r/{story.subreddit}
                </a>
                . It is not a retelling, reproduction, or summary of any specific post or real event.
                All characters, names, and details are fictional.
              </p>
            </div>

            {/* Legal disclaimer */}
            <div style={{
              background: '#0F0F0F',
              border: '1px solid rgba(255,51,51,0.1)',
              padding: '20px 24px',
              marginBottom: '60px',
            }}>
              <p style={{
                color: '#444444',
                fontSize: '0.75rem',
                lineHeight: 1.6,
                margin: 0,
                fontFamily: 'var(--font-inter), Arial, sans-serif',
              }}>
                Stories on this page are works of fiction created by AI. They are inspired by the general
                themes of public internet discussions but are not reproductions, summaries, or representations
                of any specific real post or person. All names, details, and events are fictional.
              </p>
            </div>
          </article>

          {/* Internal backlinks */}
          <div style={{
            background: '#0F0F0F',
            border: '1px solid rgba(255,215,0,0.1)',
            padding: '28px',
            marginBottom: '40px',
          }}>
            <p style={{
              fontFamily: 'var(--font-bebas), Arial, sans-serif',
              fontSize: '0.85rem',
              letterSpacing: '0.2em',
              color: '#555555',
              margin: '0 0 16px',
              textTransform: 'uppercase',
            }}>
              More from Spaghetti Burritos
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <p style={{ margin: 0, fontSize: '0.9rem', color: '#AAAAAA', fontFamily: 'var(--font-inter), Arial, sans-serif' }}>
                More AI chaos lives at{' '}
                <Link href="/" style={{ color: '#FFD700', textDecoration: 'none' }}>
                  Spaghetti Burritos
                </Link>
                {' '}— the internet&rsquo;s premier source of fictional nonsense.
              </p>
              <p style={{ margin: 0, fontSize: '0.9rem', color: '#AAAAAA', fontFamily: 'var(--font-inter), Arial, sans-serif' }}>
                Got your own situation?{' '}
                <Link href="/submit-drama" style={{ color: '#FFD700', textDecoration: 'none' }}>
                  Submit your drama
                </Link>
                {' '}and let the AI turn it into something beautiful.
              </p>
            </div>
          </div>

          {/* CTA */}
          <div style={{
            background: '#141414',
            border: '2px solid rgba(255,215,0,0.2)',
            padding: '40px',
            textAlign: 'center',
          }}>
            <h2 style={{
              fontFamily: 'var(--font-bebas), "Arial Black", Arial, sans-serif',
              fontSize: 'clamp(1.8rem, 5vw, 3rem)',
              color: '#F0F0F0',
              margin: '0 0 12px',
              letterSpacing: '0.02em',
            }}>
              GOT YOUR OWN <span style={{ color: '#FFD700' }}>DRAMA?</span>
            </h2>
            <p style={{
              color: '#888888',
              fontSize: '0.95rem',
              lineHeight: 1.7,
              margin: '0 0 24px',
              fontFamily: 'var(--font-inter), Arial, sans-serif',
            }}>
              Drop the tea. Our AI turns your mess into a masterpiece.
            </p>
            <Link href="/submit-drama" style={{
              background: '#FFD700',
              color: '#0A0A0A',
              textDecoration: 'none',
              padding: '16px 40px',
              fontFamily: 'var(--font-bebas), Arial, sans-serif',
              fontSize: '1.2rem',
              letterSpacing: '0.1em',
              display: 'inline-block',
            }}>
              SUBMIT YOUR DRAMA
            </Link>
          </div>
        </main>
      </div>
    </>
  );
}
