"use client";

import { useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import Link from "next/link";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

interface StoryData {
  headline: string;
  story: string;
  moral: string;
  date: string;
}

function FictionBanner() {
  return (
    <div
      style={{
        background: "#FF3333",
        color: "#FFFFFF",
        fontSize: "0.85rem",
        fontWeight: 900,
        letterSpacing: "0.2em",
        textTransform: "uppercase",
        padding: "16px 24px",
        textAlign: "center",
        width: "100%",
        boxSizing: "border-box",
      }}
    >
      THIS IS A WORK OF FICTION — AI-generated from an anonymous submission. All details are fictional.
    </div>
  );
}

function NoStory() {
  return (
    <div
      style={{
        background: "#0A0A0A",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <Nav />
      <div
        style={{
          flex: 1,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "80px 24px",
          textAlign: "center",
          flexDirection: "column",
          gap: "24px",
        }}
      >
        <h1
          style={{
            fontFamily: "var(--font-bebas), 'Arial Black', Arial, sans-serif",
            fontSize: "clamp(2.5rem, 8vw, 5rem)",
            color: "#F0F0F0",
            margin: 0,
            letterSpacing: "0.02em",
          }}
        >
          NO STORY FOUND
        </h1>
        <p
          style={{
            color: "#888888",
            fontSize: "1rem",
            lineHeight: 1.7,
            maxWidth: "480px",
            margin: 0,
          }}
        >
          This link doesn&rsquo;t have a story attached — or the data got corrupted somewhere along the way.
        </p>
        <Link
          href="/submit-drama"
          style={{
            background: "#FFD700",
            color: "#0A0A0A",
            textDecoration: "none",
            padding: "16px 40px",
            fontFamily: "var(--font-bebas), Arial, sans-serif",
            fontSize: "1.2rem",
            letterSpacing: "0.1em",
            display: "inline-block",
            marginTop: "8px",
          }}
        >
          SUBMIT YOUR OWN DRAMA
        </Link>
      </div>
      <Footer />
    </div>
  );
}

function RenderStory({ headline, story, moral, date }: StoryData) {
  const [linkCopied, setLinkCopied] = useState(false);

  const formattedDate = (() => {
    try {
      return new Date(date).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    } catch {
      return "Date unknown";
    }
  })();

  async function handleCopyLink() {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2500);
    } catch {
      setLinkCopied(false);
    }
  }

  function getTwitterShareUrl() {
    const text = encodeURIComponent(
      `"${headline}" — AI-generated fiction from an anonymous submission:`
    );
    const url = encodeURIComponent(window.location.href);
    return `https://twitter.com/intent/tweet?text=${text}&url=${url}`;
  }

  return (
    <div style={{ background: "#0A0A0A", minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      <Nav />

      {/* Fiction banner — impossible to miss */}
      <FictionBanner />

      {/* Full disclaimer */}
      <div
        style={{
          background: "#0F0F0F",
          borderBottom: "1px solid rgba(255,51,51,0.2)",
          padding: "16px 24px",
          textAlign: "center",
        }}
      >
        <p
          style={{
            color: "#888888",
            fontSize: "0.8rem",
            lineHeight: 1.6,
            margin: "0 auto",
            maxWidth: "800px",
            fontFamily: "var(--font-inter), Arial, sans-serif",
          }}
        >
          This story was generated by AI from an anonymous submission. All details are fictional.
          Any resemblance to actual persons, living or dead, is purely coincidental.
          Spaghetti Burritos created the fictional elements — the facts came from someone else.
        </p>
      </div>

      {/* Main content */}
      <main style={{ flex: 1, maxWidth: "740px", margin: "0 auto", padding: "48px 24px 80px", width: "100%" }}>
        {/* Date */}
        <p
          style={{
            color: "#555555",
            fontSize: "0.78rem",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            margin: "0 0 24px",
            fontFamily: "var(--font-bebas), Arial, sans-serif",
          }}
        >
          Published {formattedDate}
        </p>

        {/* Headline */}
        <h1
          style={{
            fontFamily: "var(--font-bebas), 'Arial Black', Arial, sans-serif",
            fontSize: "clamp(2.5rem, 7vw, 5rem)",
            lineHeight: 0.95,
            color: "#FFD700",
            margin: "0 0 40px",
            letterSpacing: "0.02em",
          }}
        >
          {headline}
        </h1>

        {/* Story body */}
        <div
          style={{
            color: "#D0D0D0",
            fontSize: "1.05rem",
            lineHeight: 1.9,
            marginBottom: "40px",
            whiteSpace: "pre-wrap",
            fontFamily: "var(--font-inter), Arial, sans-serif",
          }}
        >
          {story}
        </div>

        {/* Moral */}
        <div
          style={{
            borderLeft: "4px solid #FFD700",
            paddingLeft: "24px",
            marginBottom: "60px",
          }}
        >
          <p
            style={{
              color: "#888888",
              fontSize: "0.8rem",
              fontWeight: 700,
              letterSpacing: "0.15em",
              textTransform: "uppercase",
              margin: "0 0 8px",
              fontFamily: "var(--font-bebas), Arial, sans-serif",
            }}
          >
            Moral of the Story
          </p>
          <p
            style={{
              color: "#D0D0D0",
              fontSize: "1.05rem",
              lineHeight: 1.7,
              fontStyle: "italic",
              margin: 0,
              fontFamily: "var(--font-inter), Arial, sans-serif",
            }}
          >
            {moral}
          </p>
        </div>

        {/* Share buttons */}
        <div
          style={{
            borderTop: "1px solid rgba(255,215,0,0.15)",
            paddingTop: "32px",
            marginBottom: "60px",
          }}
        >
          <p
            style={{
              fontFamily: "var(--font-bebas), Arial, sans-serif",
              fontSize: "0.9rem",
              letterSpacing: "0.15em",
              color: "#888888",
              margin: "0 0 16px",
              textTransform: "uppercase",
            }}
          >
            Share This Story
          </p>
          <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
            <button
              onClick={handleCopyLink}
              style={{
                background: linkCopied ? "#333333" : "#FFD700",
                color: linkCopied ? "#F0F0F0" : "#0A0A0A",
                border: "none",
                padding: "12px 28px",
                fontFamily: "var(--font-bebas), Arial, sans-serif",
                fontSize: "1rem",
                letterSpacing: "0.1em",
                cursor: "pointer",
                transition: "background 0.2s, color 0.2s",
              }}
            >
              {linkCopied ? "LINK COPIED" : "COPY LINK"}
            </button>
            <a
              href={getTwitterShareUrl()}
              target="_blank"
              rel="noopener noreferrer"
              style={{
                background: "#1DA1F2",
                color: "#FFFFFF",
                textDecoration: "none",
                padding: "12px 28px",
                fontFamily: "var(--font-bebas), Arial, sans-serif",
                fontSize: "1rem",
                letterSpacing: "0.1em",
                display: "inline-block",
                transition: "background 0.2s",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.background = "#1a8fd1")}
              onMouseLeave={(e) => (e.currentTarget.style.background = "#1DA1F2")}
            >
              SHARE ON X
            </a>
          </div>
        </div>

        {/* CTA */}
        <div
          style={{
            background: "#141414",
            border: "2px solid rgba(255,215,0,0.2)",
            padding: "40px",
            textAlign: "center",
          }}
        >
          <h2
            style={{
              fontFamily: "var(--font-bebas), 'Arial Black', Arial, sans-serif",
              fontSize: "clamp(1.8rem, 5vw, 3rem)",
              color: "#F0F0F0",
              margin: "0 0 12px",
              letterSpacing: "0.02em",
            }}
          >
            GOT YOUR OWN <span style={{ color: "#FFD700" }}>DRAMA?</span>
          </h2>
          <p
            style={{
              color: "#888888",
              fontSize: "0.95rem",
              lineHeight: 1.7,
              margin: "0 0 24px",
              fontFamily: "var(--font-inter), Arial, sans-serif",
            }}
          >
            Drop the tea. Our AI turns your mess into a masterpiece.
          </p>
          <Link
            href="/submit-drama"
            style={{
              background: "#FFD700",
              color: "#0A0A0A",
              textDecoration: "none",
              padding: "16px 40px",
              fontFamily: "var(--font-bebas), Arial, sans-serif",
              fontSize: "1.2rem",
              letterSpacing: "0.1em",
              display: "inline-block",
              transition: "background 0.2s",
            }}
            onMouseEnter={(e) => (e.currentTarget.style.background = "#FFC200")}
            onMouseLeave={(e) => (e.currentTarget.style.background = "#FFD700")}
          >
            SUBMIT YOUR DRAMA
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}

function StoryContent() {
  const params = useSearchParams();
  const d = params.get("d");

  if (!d) return <NoStory />;

  try {
    const data: StoryData = JSON.parse(decodeURIComponent(atob(d)));
    if (!data.headline || !data.story || !data.moral) return <NoStory />;
    return (
      <RenderStory
        headline={data.headline}
        story={data.story}
        moral={data.moral}
        date={data.date}
      />
    );
  } catch {
    return <NoStory />;
  }
}

export default function StoriesPage() {
  return (
    <Suspense
      fallback={
        <div
          style={{
            background: "#0A0A0A",
            minHeight: "100vh",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <p
            style={{
              fontFamily: "var(--font-bebas), Arial, sans-serif",
              fontSize: "1.5rem",
              letterSpacing: "0.1em",
              color: "#555555",
            }}
          >
            LOADING...
          </p>
        </div>
      }
    >
      <StoryContent />
    </Suspense>
  );
}
